// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/material_protobuf.proto

#include "proto/material_protobuf.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace material_protobuf {
class Library_Material_ScalarPropertyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Library_Material_ScalarProperty>
      _instance;
} _Library_Material_ScalarProperty_default_instance_;
class Library_Material_VectorPropertyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Library_Material_VectorProperty>
      _instance;
} _Library_Material_VectorProperty_default_instance_;
class Library_Material_MatrixPropertyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Library_Material_MatrixProperty>
      _instance;
} _Library_Material_MatrixProperty_default_instance_;
class Library_MaterialDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Library_Material>
      _instance;
} _Library_Material_default_instance_;
class LibraryDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Library>
      _instance;
} _Library_default_instance_;
}  // namespace material_protobuf
namespace protobuf_proto_2fmaterial_5fprotobuf_2eproto {
void InitDefaultsLibrary_Material_ScalarPropertyImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::material_protobuf::_Library_Material_ScalarProperty_default_instance_;
    new (ptr) ::material_protobuf::Library_Material_ScalarProperty();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::material_protobuf::Library_Material_ScalarProperty::InitAsDefaultInstance();
}

void InitDefaultsLibrary_Material_ScalarProperty() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLibrary_Material_ScalarPropertyImpl);
}

void InitDefaultsLibrary_Material_VectorPropertyImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::material_protobuf::_Library_Material_VectorProperty_default_instance_;
    new (ptr) ::material_protobuf::Library_Material_VectorProperty();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::material_protobuf::Library_Material_VectorProperty::InitAsDefaultInstance();
}

void InitDefaultsLibrary_Material_VectorProperty() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLibrary_Material_VectorPropertyImpl);
}

void InitDefaultsLibrary_Material_MatrixPropertyImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::material_protobuf::_Library_Material_MatrixProperty_default_instance_;
    new (ptr) ::material_protobuf::Library_Material_MatrixProperty();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::material_protobuf::Library_Material_MatrixProperty::InitAsDefaultInstance();
}

void InitDefaultsLibrary_Material_MatrixProperty() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLibrary_Material_MatrixPropertyImpl);
}

void InitDefaultsLibrary_MaterialImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_ScalarProperty();
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_VectorProperty();
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_MatrixProperty();
  {
    void* ptr = &::material_protobuf::_Library_Material_default_instance_;
    new (ptr) ::material_protobuf::Library_Material();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::material_protobuf::Library_Material::InitAsDefaultInstance();
}

void InitDefaultsLibrary_Material() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLibrary_MaterialImpl);
}

void InitDefaultsLibraryImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material();
  {
    void* ptr = &::material_protobuf::_Library_default_instance_;
    new (ptr) ::material_protobuf::Library();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::material_protobuf::Library::InitAsDefaultInstance();
}

void InitDefaultsLibrary() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLibraryImpl);
}

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_ScalarProperty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_ScalarProperty, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_ScalarProperty, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_VectorProperty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_VectorProperty, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_VectorProperty, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_MatrixProperty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_MatrixProperty, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_MatrixProperty, rows_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_MatrixProperty, cols_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material_MatrixProperty, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, full_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, abbreviation_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, a_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, scalar_property_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, vector_property_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library_Material, matrix_property_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library, library_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library, number_of_groups_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library, energy_groups_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::material_protobuf::Library, materials_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::material_protobuf::Library_Material_ScalarProperty)},
  { 7, -1, sizeof(::material_protobuf::Library_Material_VectorProperty)},
  { 14, -1, sizeof(::material_protobuf::Library_Material_MatrixProperty)},
  { 23, -1, sizeof(::material_protobuf::Library_Material)},
  { 35, -1, sizeof(::material_protobuf::Library)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::material_protobuf::_Library_Material_ScalarProperty_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::material_protobuf::_Library_Material_VectorProperty_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::material_protobuf::_Library_Material_MatrixProperty_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::material_protobuf::_Library_Material_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::material_protobuf::_Library_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto/material_protobuf.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035proto/material_protobuf.proto\022\021materia"
      "l_protobuf\"\351\006\n\007Library\022\024\n\014library_name\030\001"
      " \001(\t\022\030\n\020number_of_groups\030\002 \001(\r\022\031\n\renergy"
      "_groups\030\003 \003(\002B\002\020\001\0226\n\tmaterials\030\004 \003(\0132#.m"
      "aterial_protobuf.Library.Material\032\312\004\n\010Ma"
      "terial\022\021\n\tfull_name\030\001 \001(\t\022\024\n\014abbreviatio"
      "n\030\002 \001(\t\022\t\n\001A\030\003 \001(\r\022\t\n\001Z\030\004 \001(\r\022K\n\017scalar_"
      "property\030\005 \003(\01322.material_protobuf.Libra"
      "ry.Material.ScalarProperty\022K\n\017vector_pro"
      "perty\030\006 \003(\01322.material_protobuf.Library."
      "Material.VectorProperty\022K\n\017matrix_proper"
      "ty\030\007 \003(\01322.material_protobuf.Library.Mat"
      "erial.MatrixProperty\032P\n\016ScalarProperty\022/"
      "\n\002id\030\001 \001(\0162#.material_protobuf.Library.S"
      "calarId\022\r\n\005value\030\002 \001(\002\032T\n\016VectorProperty"
      "\022/\n\002id\030\001 \001(\0162#.material_protobuf.Library"
      ".VectorId\022\021\n\005value\030\002 \003(\001B\002\020\001\032p\n\016MatrixPr"
      "operty\022/\n\002id\030\001 \001(\0162#.material_protobuf.L"
      "ibrary.MatrixId\022\014\n\004rows\030\002 \001(\r\022\014\n\004cols\030\003 "
      "\001(\r\022\021\n\005value\030\004 \003(\001B\002\020\001\"+\n\010ScalarId\022\022\n\016UN"
      "KNOWN_SCALAR\020\000\022\013\n\007DENSITY\020\001\"4\n\010VectorId\022"
      "\022\n\016UNKNOWN_VECTOR\020\000\022\013\n\007SIGMA_T\020\001\022\007\n\003CHI\020"
      "\002\"+\n\010MatrixId\022\022\n\016UNKNOWN_MATRIX\020\000\022\013\n\007SIG"
      "MA_S\020\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 934);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/material_protobuf.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_2fmaterial_5fprotobuf_2eproto
namespace material_protobuf {
const ::google::protobuf::EnumDescriptor* Library_ScalarId_descriptor() {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_enum_descriptors[0];
}
bool Library_ScalarId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Library_ScalarId Library::UNKNOWN_SCALAR;
const Library_ScalarId Library::DENSITY;
const Library_ScalarId Library::ScalarId_MIN;
const Library_ScalarId Library::ScalarId_MAX;
const int Library::ScalarId_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Library_VectorId_descriptor() {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_enum_descriptors[1];
}
bool Library_VectorId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Library_VectorId Library::UNKNOWN_VECTOR;
const Library_VectorId Library::SIGMA_T;
const Library_VectorId Library::CHI;
const Library_VectorId Library::VectorId_MIN;
const Library_VectorId Library::VectorId_MAX;
const int Library::VectorId_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Library_MatrixId_descriptor() {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_enum_descriptors[2];
}
bool Library_MatrixId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Library_MatrixId Library::UNKNOWN_MATRIX;
const Library_MatrixId Library::SIGMA_S;
const Library_MatrixId Library::MatrixId_MIN;
const Library_MatrixId Library::MatrixId_MAX;
const int Library::MatrixId_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void Library_Material_ScalarProperty::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Library_Material_ScalarProperty::kIdFieldNumber;
const int Library_Material_ScalarProperty::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Library_Material_ScalarProperty::Library_Material_ScalarProperty()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_ScalarProperty();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:material_protobuf.Library.Material.ScalarProperty)
}
Library_Material_ScalarProperty::Library_Material_ScalarProperty(const Library_Material_ScalarProperty& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&id_)) + sizeof(value_));
  // @@protoc_insertion_point(copy_constructor:material_protobuf.Library.Material.ScalarProperty)
}

void Library_Material_ScalarProperty::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&id_)) + sizeof(value_));
  _cached_size_ = 0;
}

Library_Material_ScalarProperty::~Library_Material_ScalarProperty() {
  // @@protoc_insertion_point(destructor:material_protobuf.Library.Material.ScalarProperty)
  SharedDtor();
}

void Library_Material_ScalarProperty::SharedDtor() {
}

void Library_Material_ScalarProperty::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Library_Material_ScalarProperty::descriptor() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Library_Material_ScalarProperty& Library_Material_ScalarProperty::default_instance() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_ScalarProperty();
  return *internal_default_instance();
}

Library_Material_ScalarProperty* Library_Material_ScalarProperty::New(::google::protobuf::Arena* arena) const {
  Library_Material_ScalarProperty* n = new Library_Material_ScalarProperty;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Library_Material_ScalarProperty::Clear() {
// @@protoc_insertion_point(message_clear_start:material_protobuf.Library.Material.ScalarProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&id_)) + sizeof(value_));
  _internal_metadata_.Clear();
}

bool Library_Material_ScalarProperty::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:material_protobuf.Library.Material.ScalarProperty)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .material_protobuf.Library.ScalarId id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_id(static_cast< ::material_protobuf::Library_ScalarId >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:material_protobuf.Library.Material.ScalarProperty)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:material_protobuf.Library.Material.ScalarProperty)
  return false;
#undef DO_
}

void Library_Material_ScalarProperty::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:material_protobuf.Library.Material.ScalarProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .material_protobuf.Library.ScalarId id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->id(), output);
  }

  // float value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:material_protobuf.Library.Material.ScalarProperty)
}

::google::protobuf::uint8* Library_Material_ScalarProperty::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:material_protobuf.Library.Material.ScalarProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .material_protobuf.Library.ScalarId id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->id(), target);
  }

  // float value = 2;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:material_protobuf.Library.Material.ScalarProperty)
  return target;
}

size_t Library_Material_ScalarProperty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:material_protobuf.Library.Material.ScalarProperty)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .material_protobuf.Library.ScalarId id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->id());
  }

  // float value = 2;
  if (this->value() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Library_Material_ScalarProperty::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:material_protobuf.Library.Material.ScalarProperty)
  GOOGLE_DCHECK_NE(&from, this);
  const Library_Material_ScalarProperty* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Library_Material_ScalarProperty>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:material_protobuf.Library.Material.ScalarProperty)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:material_protobuf.Library.Material.ScalarProperty)
    MergeFrom(*source);
  }
}

void Library_Material_ScalarProperty::MergeFrom(const Library_Material_ScalarProperty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:material_protobuf.Library.Material.ScalarProperty)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void Library_Material_ScalarProperty::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:material_protobuf.Library.Material.ScalarProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Library_Material_ScalarProperty::CopyFrom(const Library_Material_ScalarProperty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:material_protobuf.Library.Material.ScalarProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Library_Material_ScalarProperty::IsInitialized() const {
  return true;
}

void Library_Material_ScalarProperty::Swap(Library_Material_ScalarProperty* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Library_Material_ScalarProperty::InternalSwap(Library_Material_ScalarProperty* other) {
  using std::swap;
  swap(id_, other->id_);
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Library_Material_ScalarProperty::GetMetadata() const {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Library_Material_VectorProperty::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Library_Material_VectorProperty::kIdFieldNumber;
const int Library_Material_VectorProperty::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Library_Material_VectorProperty::Library_Material_VectorProperty()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_VectorProperty();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:material_protobuf.Library.Material.VectorProperty)
}
Library_Material_VectorProperty::Library_Material_VectorProperty(const Library_Material_VectorProperty& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      value_(from.value_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:material_protobuf.Library.Material.VectorProperty)
}

void Library_Material_VectorProperty::SharedCtor() {
  id_ = 0;
  _cached_size_ = 0;
}

Library_Material_VectorProperty::~Library_Material_VectorProperty() {
  // @@protoc_insertion_point(destructor:material_protobuf.Library.Material.VectorProperty)
  SharedDtor();
}

void Library_Material_VectorProperty::SharedDtor() {
}

void Library_Material_VectorProperty::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Library_Material_VectorProperty::descriptor() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Library_Material_VectorProperty& Library_Material_VectorProperty::default_instance() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_VectorProperty();
  return *internal_default_instance();
}

Library_Material_VectorProperty* Library_Material_VectorProperty::New(::google::protobuf::Arena* arena) const {
  Library_Material_VectorProperty* n = new Library_Material_VectorProperty;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Library_Material_VectorProperty::Clear() {
// @@protoc_insertion_point(message_clear_start:material_protobuf.Library.Material.VectorProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.Clear();
  id_ = 0;
  _internal_metadata_.Clear();
}

bool Library_Material_VectorProperty::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:material_protobuf.Library.Material.VectorProperty)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .material_protobuf.Library.VectorId id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_id(static_cast< ::material_protobuf::Library_VectorId >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double value = 2 [packed = true];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_value())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 18u, input, this->mutable_value())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:material_protobuf.Library.Material.VectorProperty)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:material_protobuf.Library.Material.VectorProperty)
  return false;
#undef DO_
}

void Library_Material_VectorProperty::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:material_protobuf.Library.Material.VectorProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .material_protobuf.Library.VectorId id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->id(), output);
  }

  // repeated double value = 2 [packed = true];
  if (this->value_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _value_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->value().data(), this->value_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:material_protobuf.Library.Material.VectorProperty)
}

::google::protobuf::uint8* Library_Material_VectorProperty::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:material_protobuf.Library.Material.VectorProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .material_protobuf.Library.VectorId id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->id(), target);
  }

  // repeated double value = 2 [packed = true];
  if (this->value_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _value_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->value_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:material_protobuf.Library.Material.VectorProperty)
  return target;
}

size_t Library_Material_VectorProperty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:material_protobuf.Library.Material.VectorProperty)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated double value = 2 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->value_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _value_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // .material_protobuf.Library.VectorId id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Library_Material_VectorProperty::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:material_protobuf.Library.Material.VectorProperty)
  GOOGLE_DCHECK_NE(&from, this);
  const Library_Material_VectorProperty* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Library_Material_VectorProperty>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:material_protobuf.Library.Material.VectorProperty)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:material_protobuf.Library.Material.VectorProperty)
    MergeFrom(*source);
  }
}

void Library_Material_VectorProperty::MergeFrom(const Library_Material_VectorProperty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:material_protobuf.Library.Material.VectorProperty)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  value_.MergeFrom(from.value_);
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void Library_Material_VectorProperty::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:material_protobuf.Library.Material.VectorProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Library_Material_VectorProperty::CopyFrom(const Library_Material_VectorProperty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:material_protobuf.Library.Material.VectorProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Library_Material_VectorProperty::IsInitialized() const {
  return true;
}

void Library_Material_VectorProperty::Swap(Library_Material_VectorProperty* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Library_Material_VectorProperty::InternalSwap(Library_Material_VectorProperty* other) {
  using std::swap;
  value_.InternalSwap(&other->value_);
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Library_Material_VectorProperty::GetMetadata() const {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Library_Material_MatrixProperty::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Library_Material_MatrixProperty::kIdFieldNumber;
const int Library_Material_MatrixProperty::kRowsFieldNumber;
const int Library_Material_MatrixProperty::kColsFieldNumber;
const int Library_Material_MatrixProperty::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Library_Material_MatrixProperty::Library_Material_MatrixProperty()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_MatrixProperty();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:material_protobuf.Library.Material.MatrixProperty)
}
Library_Material_MatrixProperty::Library_Material_MatrixProperty(const Library_Material_MatrixProperty& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      value_(from.value_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&cols_) -
    reinterpret_cast<char*>(&id_)) + sizeof(cols_));
  // @@protoc_insertion_point(copy_constructor:material_protobuf.Library.Material.MatrixProperty)
}

void Library_Material_MatrixProperty::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cols_) -
      reinterpret_cast<char*>(&id_)) + sizeof(cols_));
  _cached_size_ = 0;
}

Library_Material_MatrixProperty::~Library_Material_MatrixProperty() {
  // @@protoc_insertion_point(destructor:material_protobuf.Library.Material.MatrixProperty)
  SharedDtor();
}

void Library_Material_MatrixProperty::SharedDtor() {
}

void Library_Material_MatrixProperty::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Library_Material_MatrixProperty::descriptor() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Library_Material_MatrixProperty& Library_Material_MatrixProperty::default_instance() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material_MatrixProperty();
  return *internal_default_instance();
}

Library_Material_MatrixProperty* Library_Material_MatrixProperty::New(::google::protobuf::Arena* arena) const {
  Library_Material_MatrixProperty* n = new Library_Material_MatrixProperty;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Library_Material_MatrixProperty::Clear() {
// @@protoc_insertion_point(message_clear_start:material_protobuf.Library.Material.MatrixProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.Clear();
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cols_) -
      reinterpret_cast<char*>(&id_)) + sizeof(cols_));
  _internal_metadata_.Clear();
}

bool Library_Material_MatrixProperty::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:material_protobuf.Library.Material.MatrixProperty)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .material_protobuf.Library.MatrixId id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_id(static_cast< ::material_protobuf::Library_MatrixId >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 rows = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rows_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 cols = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cols_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double value = 4 [packed = true];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_value())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 34u, input, this->mutable_value())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:material_protobuf.Library.Material.MatrixProperty)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:material_protobuf.Library.Material.MatrixProperty)
  return false;
#undef DO_
}

void Library_Material_MatrixProperty::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:material_protobuf.Library.Material.MatrixProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .material_protobuf.Library.MatrixId id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->id(), output);
  }

  // uint32 rows = 2;
  if (this->rows() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->rows(), output);
  }

  // uint32 cols = 3;
  if (this->cols() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->cols(), output);
  }

  // repeated double value = 4 [packed = true];
  if (this->value_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _value_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->value().data(), this->value_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:material_protobuf.Library.Material.MatrixProperty)
}

::google::protobuf::uint8* Library_Material_MatrixProperty::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:material_protobuf.Library.Material.MatrixProperty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .material_protobuf.Library.MatrixId id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->id(), target);
  }

  // uint32 rows = 2;
  if (this->rows() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->rows(), target);
  }

  // uint32 cols = 3;
  if (this->cols() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->cols(), target);
  }

  // repeated double value = 4 [packed = true];
  if (this->value_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _value_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->value_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:material_protobuf.Library.Material.MatrixProperty)
  return target;
}

size_t Library_Material_MatrixProperty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:material_protobuf.Library.Material.MatrixProperty)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated double value = 4 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->value_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _value_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // .material_protobuf.Library.MatrixId id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->id());
  }

  // uint32 rows = 2;
  if (this->rows() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->rows());
  }

  // uint32 cols = 3;
  if (this->cols() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->cols());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Library_Material_MatrixProperty::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:material_protobuf.Library.Material.MatrixProperty)
  GOOGLE_DCHECK_NE(&from, this);
  const Library_Material_MatrixProperty* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Library_Material_MatrixProperty>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:material_protobuf.Library.Material.MatrixProperty)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:material_protobuf.Library.Material.MatrixProperty)
    MergeFrom(*source);
  }
}

void Library_Material_MatrixProperty::MergeFrom(const Library_Material_MatrixProperty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:material_protobuf.Library.Material.MatrixProperty)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  value_.MergeFrom(from.value_);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.rows() != 0) {
    set_rows(from.rows());
  }
  if (from.cols() != 0) {
    set_cols(from.cols());
  }
}

void Library_Material_MatrixProperty::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:material_protobuf.Library.Material.MatrixProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Library_Material_MatrixProperty::CopyFrom(const Library_Material_MatrixProperty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:material_protobuf.Library.Material.MatrixProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Library_Material_MatrixProperty::IsInitialized() const {
  return true;
}

void Library_Material_MatrixProperty::Swap(Library_Material_MatrixProperty* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Library_Material_MatrixProperty::InternalSwap(Library_Material_MatrixProperty* other) {
  using std::swap;
  value_.InternalSwap(&other->value_);
  swap(id_, other->id_);
  swap(rows_, other->rows_);
  swap(cols_, other->cols_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Library_Material_MatrixProperty::GetMetadata() const {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Library_Material::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Library_Material::kFullNameFieldNumber;
const int Library_Material::kAbbreviationFieldNumber;
const int Library_Material::kAFieldNumber;
const int Library_Material::kZFieldNumber;
const int Library_Material::kScalarPropertyFieldNumber;
const int Library_Material::kVectorPropertyFieldNumber;
const int Library_Material::kMatrixPropertyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Library_Material::Library_Material()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:material_protobuf.Library.Material)
}
Library_Material::Library_Material(const Library_Material& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      scalar_property_(from.scalar_property_),
      vector_property_(from.vector_property_),
      matrix_property_(from.matrix_property_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  full_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.full_name().size() > 0) {
    full_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.full_name_);
  }
  abbreviation_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.abbreviation().size() > 0) {
    abbreviation_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.abbreviation_);
  }
  ::memcpy(&a_, &from.a_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&a_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:material_protobuf.Library.Material)
}

void Library_Material::SharedCtor() {
  full_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  abbreviation_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&a_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&a_)) + sizeof(z_));
  _cached_size_ = 0;
}

Library_Material::~Library_Material() {
  // @@protoc_insertion_point(destructor:material_protobuf.Library.Material)
  SharedDtor();
}

void Library_Material::SharedDtor() {
  full_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  abbreviation_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Library_Material::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Library_Material::descriptor() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Library_Material& Library_Material::default_instance() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary_Material();
  return *internal_default_instance();
}

Library_Material* Library_Material::New(::google::protobuf::Arena* arena) const {
  Library_Material* n = new Library_Material;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Library_Material::Clear() {
// @@protoc_insertion_point(message_clear_start:material_protobuf.Library.Material)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  scalar_property_.Clear();
  vector_property_.Clear();
  matrix_property_.Clear();
  full_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  abbreviation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&a_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&a_)) + sizeof(z_));
  _internal_metadata_.Clear();
}

bool Library_Material::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:material_protobuf.Library.Material)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string full_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_full_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->full_name().data(), static_cast<int>(this->full_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "material_protobuf.Library.Material.full_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string abbreviation = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_abbreviation()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->abbreviation().data(), static_cast<int>(this->abbreviation().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "material_protobuf.Library.Material.abbreviation"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 A = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &a_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 Z = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .material_protobuf.Library.Material.ScalarProperty scalar_property = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_scalar_property()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .material_protobuf.Library.Material.VectorProperty vector_property = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_vector_property()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .material_protobuf.Library.Material.MatrixProperty matrix_property = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_matrix_property()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:material_protobuf.Library.Material)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:material_protobuf.Library.Material)
  return false;
#undef DO_
}

void Library_Material::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:material_protobuf.Library.Material)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string full_name = 1;
  if (this->full_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->full_name().data(), static_cast<int>(this->full_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "material_protobuf.Library.Material.full_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->full_name(), output);
  }

  // string abbreviation = 2;
  if (this->abbreviation().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->abbreviation().data(), static_cast<int>(this->abbreviation().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "material_protobuf.Library.Material.abbreviation");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->abbreviation(), output);
  }

  // uint32 A = 3;
  if (this->a() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->a(), output);
  }

  // uint32 Z = 4;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->z(), output);
  }

  // repeated .material_protobuf.Library.Material.ScalarProperty scalar_property = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->scalar_property_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->scalar_property(static_cast<int>(i)), output);
  }

  // repeated .material_protobuf.Library.Material.VectorProperty vector_property = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->vector_property_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->vector_property(static_cast<int>(i)), output);
  }

  // repeated .material_protobuf.Library.Material.MatrixProperty matrix_property = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->matrix_property_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->matrix_property(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:material_protobuf.Library.Material)
}

::google::protobuf::uint8* Library_Material::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:material_protobuf.Library.Material)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string full_name = 1;
  if (this->full_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->full_name().data(), static_cast<int>(this->full_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "material_protobuf.Library.Material.full_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->full_name(), target);
  }

  // string abbreviation = 2;
  if (this->abbreviation().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->abbreviation().data(), static_cast<int>(this->abbreviation().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "material_protobuf.Library.Material.abbreviation");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->abbreviation(), target);
  }

  // uint32 A = 3;
  if (this->a() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->a(), target);
  }

  // uint32 Z = 4;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->z(), target);
  }

  // repeated .material_protobuf.Library.Material.ScalarProperty scalar_property = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->scalar_property_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->scalar_property(static_cast<int>(i)), deterministic, target);
  }

  // repeated .material_protobuf.Library.Material.VectorProperty vector_property = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->vector_property_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->vector_property(static_cast<int>(i)), deterministic, target);
  }

  // repeated .material_protobuf.Library.Material.MatrixProperty matrix_property = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->matrix_property_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, this->matrix_property(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:material_protobuf.Library.Material)
  return target;
}

size_t Library_Material::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:material_protobuf.Library.Material)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .material_protobuf.Library.Material.ScalarProperty scalar_property = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->scalar_property_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->scalar_property(static_cast<int>(i)));
    }
  }

  // repeated .material_protobuf.Library.Material.VectorProperty vector_property = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->vector_property_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->vector_property(static_cast<int>(i)));
    }
  }

  // repeated .material_protobuf.Library.Material.MatrixProperty matrix_property = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->matrix_property_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->matrix_property(static_cast<int>(i)));
    }
  }

  // string full_name = 1;
  if (this->full_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->full_name());
  }

  // string abbreviation = 2;
  if (this->abbreviation().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->abbreviation());
  }

  // uint32 A = 3;
  if (this->a() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->a());
  }

  // uint32 Z = 4;
  if (this->z() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->z());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Library_Material::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:material_protobuf.Library.Material)
  GOOGLE_DCHECK_NE(&from, this);
  const Library_Material* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Library_Material>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:material_protobuf.Library.Material)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:material_protobuf.Library.Material)
    MergeFrom(*source);
  }
}

void Library_Material::MergeFrom(const Library_Material& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:material_protobuf.Library.Material)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  scalar_property_.MergeFrom(from.scalar_property_);
  vector_property_.MergeFrom(from.vector_property_);
  matrix_property_.MergeFrom(from.matrix_property_);
  if (from.full_name().size() > 0) {

    full_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.full_name_);
  }
  if (from.abbreviation().size() > 0) {

    abbreviation_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.abbreviation_);
  }
  if (from.a() != 0) {
    set_a(from.a());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void Library_Material::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:material_protobuf.Library.Material)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Library_Material::CopyFrom(const Library_Material& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:material_protobuf.Library.Material)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Library_Material::IsInitialized() const {
  return true;
}

void Library_Material::Swap(Library_Material* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Library_Material::InternalSwap(Library_Material* other) {
  using std::swap;
  scalar_property_.InternalSwap(&other->scalar_property_);
  vector_property_.InternalSwap(&other->vector_property_);
  matrix_property_.InternalSwap(&other->matrix_property_);
  full_name_.Swap(&other->full_name_);
  abbreviation_.Swap(&other->abbreviation_);
  swap(a_, other->a_);
  swap(z_, other->z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Library_Material::GetMetadata() const {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Library::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Library::kLibraryNameFieldNumber;
const int Library::kNumberOfGroupsFieldNumber;
const int Library::kEnergyGroupsFieldNumber;
const int Library::kMaterialsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Library::Library()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:material_protobuf.Library)
}
Library::Library(const Library& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      energy_groups_(from.energy_groups_),
      materials_(from.materials_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  library_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.library_name().size() > 0) {
    library_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.library_name_);
  }
  number_of_groups_ = from.number_of_groups_;
  // @@protoc_insertion_point(copy_constructor:material_protobuf.Library)
}

void Library::SharedCtor() {
  library_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  number_of_groups_ = 0u;
  _cached_size_ = 0;
}

Library::~Library() {
  // @@protoc_insertion_point(destructor:material_protobuf.Library)
  SharedDtor();
}

void Library::SharedDtor() {
  library_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Library::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Library::descriptor() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Library& Library::default_instance() {
  ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::InitDefaultsLibrary();
  return *internal_default_instance();
}

Library* Library::New(::google::protobuf::Arena* arena) const {
  Library* n = new Library;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Library::Clear() {
// @@protoc_insertion_point(message_clear_start:material_protobuf.Library)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  energy_groups_.Clear();
  materials_.Clear();
  library_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  number_of_groups_ = 0u;
  _internal_metadata_.Clear();
}

bool Library::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:material_protobuf.Library)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string library_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_library_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->library_name().data(), static_cast<int>(this->library_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "material_protobuf.Library.library_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 number_of_groups = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_of_groups_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float energy_groups = 3 [packed = true];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_energy_groups())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 26u, input, this->mutable_energy_groups())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .material_protobuf.Library.Material materials = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_materials()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:material_protobuf.Library)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:material_protobuf.Library)
  return false;
#undef DO_
}

void Library::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:material_protobuf.Library)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string library_name = 1;
  if (this->library_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->library_name().data(), static_cast<int>(this->library_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "material_protobuf.Library.library_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->library_name(), output);
  }

  // uint32 number_of_groups = 2;
  if (this->number_of_groups() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->number_of_groups(), output);
  }

  // repeated float energy_groups = 3 [packed = true];
  if (this->energy_groups_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _energy_groups_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->energy_groups().data(), this->energy_groups_size(), output);
  }

  // repeated .material_protobuf.Library.Material materials = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->materials_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->materials(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:material_protobuf.Library)
}

::google::protobuf::uint8* Library::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:material_protobuf.Library)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string library_name = 1;
  if (this->library_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->library_name().data(), static_cast<int>(this->library_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "material_protobuf.Library.library_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->library_name(), target);
  }

  // uint32 number_of_groups = 2;
  if (this->number_of_groups() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->number_of_groups(), target);
  }

  // repeated float energy_groups = 3 [packed = true];
  if (this->energy_groups_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _energy_groups_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->energy_groups_, target);
  }

  // repeated .material_protobuf.Library.Material materials = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->materials_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->materials(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:material_protobuf.Library)
  return target;
}

size_t Library::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:material_protobuf.Library)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float energy_groups = 3 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->energy_groups_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _energy_groups_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated .material_protobuf.Library.Material materials = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->materials_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->materials(static_cast<int>(i)));
    }
  }

  // string library_name = 1;
  if (this->library_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->library_name());
  }

  // uint32 number_of_groups = 2;
  if (this->number_of_groups() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->number_of_groups());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Library::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:material_protobuf.Library)
  GOOGLE_DCHECK_NE(&from, this);
  const Library* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Library>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:material_protobuf.Library)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:material_protobuf.Library)
    MergeFrom(*source);
  }
}

void Library::MergeFrom(const Library& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:material_protobuf.Library)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  energy_groups_.MergeFrom(from.energy_groups_);
  materials_.MergeFrom(from.materials_);
  if (from.library_name().size() > 0) {

    library_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.library_name_);
  }
  if (from.number_of_groups() != 0) {
    set_number_of_groups(from.number_of_groups());
  }
}

void Library::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:material_protobuf.Library)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Library::CopyFrom(const Library& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:material_protobuf.Library)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Library::IsInitialized() const {
  return true;
}

void Library::Swap(Library* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Library::InternalSwap(Library* other) {
  using std::swap;
  energy_groups_.InternalSwap(&other->energy_groups_);
  materials_.InternalSwap(&other->materials_);
  library_name_.Swap(&other->library_name_);
  swap(number_of_groups_, other->number_of_groups_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Library::GetMetadata() const {
  protobuf_proto_2fmaterial_5fprotobuf_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmaterial_5fprotobuf_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace material_protobuf

// @@protoc_insertion_point(global_scope)
